blogs/urls.py
from django.urls import path

from blogs import views

urlpatterns = [
    path('', views.list),
    path('login/', views.mylogin),
    path('logout/', views.mylogout),
    path('signup/', views.mysignup),

    path('<int:id>/', views.detail),
    path('<int:id>/review/', views.review),


]

polls/urls.py
from django.urls import path

from polls import views

urlpatterns = [
    path('', views.list),
    path('<id>/', views.detail),
    path('<id>/vote/', views.vote),

]

web/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from polls import views
from web.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('blogs/', include("blogs.urls")),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

blogs/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Article(models.Model):
    title       = models.CharField(max_length=250)
    description = models.TextField()
    author      = models.CharField(max_length=250)
    created     = models.DateTimeField(auto_now_add=True)
    modified    = models.DateTimeField(auto_now=True)
    published   = models.BooleanField(default=True)
    image       = models.ImageField(upload_to="article", blank=True)
    view        = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Review(models.Model):
    rate = models.IntegerField(default=10)
    review = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.review

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    text = models.CharField(max_length=250,)
    created = models.DateTimeField()
    modified = models.DateTimeField()
    view = models.IntegerField(default=0)
    published = models.BooleanField(default=True)

    def __str__(self):
        return self.text

class Choice(models.Model):
    text = models.CharField(max_length=250)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField()
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.question.text + " - " + self.text

blogs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from blogs.models import Review


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ["rate", "review"]


class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class LoginForm(forms.Form):
    username = forms.CharField(max_length=250)
    password = forms.CharField(max_length=250, widget=forms.PasswordInput)

blogs/views.py
from django.shortcuts import render, redirect

# Create your views here.
from blogs.forms import ReviewForm, SignupForm, LoginForm
from blogs.models import Article


def list(req):
    blogs = Article.objects.filter(published=True)
    return render(req, "blogs/index.html", {"blogs":blogs, "len":len(blogs)})

def detail(req, id):
    blog = Article.objects.get(id=id)
    blog.view += 1
    blog.save()
    form = ReviewForm()
    return render(req, "blogs/detail.html", {"blog":blog, "form":form })

def review(req, id):
    if req.method == "POST":
        form = ReviewForm(req.POST)
        myreview = form.save(commit=False)
        myreview.article = Article.objects.get(id=id)
        myreview.user = req.user
        myreview.save()

    return redirect("/blogs/" + str(id) + "/")

def mylogin(req):
    return render(req, "blogs/login.html", {"form":LoginForm()})

def mylogout(req):
    return render(req, "blogs/index.html")

def mysignup(req):
    form = SignupForm()
    return render(req, "blogs/signup.html", {"form":form})

polls/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from polls import models


def home(req):
    return HttpResponse("<h1>Hello World</h1>")

def list(req):
    questions = models.Question.objects.all()
    context = {"questions":questions, "hello":"there"}
    return render(req, "polls/index.html", context)

def detail(req, id):
    question = models.Question.objects.get(id=id)
    dict = {"question":question}
    return render(req, "polls/detail.html", dict)

def vote(req, id):
    # increase count
    if req.method == "POST":
        selected_choice = req.POST.get("choice")
        if selected_choice:
            question = models.Question.objects.get(id=id)
            choice = question.choice_set.get(id=selected_choice)
            choice.vote += 1
            choice.save()

    return redirect("/polls/" + str(id) + "/")

def a():
    ""

def b():
    ""

blogs/templates/blogs/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/sdgs">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown link
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
      <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-12">
          <div class="alert alert-success" role="alert">
            This is sidebar
          </div>
        </div>
        <div class="col-lg-9 col-md-8 col-sm-12">
          <div class="alert alert-success" role="alert">
            This is a success alert—check it out!
          </div>
            {% block content %}
          <div class="row">
            <div class="col-6">6</div>
            <div class="col-6">6</div>
          </div>
            {% endblock %}
        </div>
      </div>

    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

blogs/templates/blogs/detail.html
{% extends "blogs/base.html" %}

{% block content %}
    <div class="card mb-3">
      <img class="card-img-top" src="/media/{{ blog.image }}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">{{ blog.title|title }}</h5>
        <p class="card-text">{{ blog.description }}</p>
        <p class="card-text">Views : {{ blog.view }}</p>
        <p class="card-text"><small class="text-muted">{{ blog.created|timesince }}</small></p>
      </div>
    </div>

    <hr>
    <p>Total reviews {{ blog.review_set.all|length }}</p>
    {% for review in blog.review_set.all %}
        <div class="card mb-3">
          <div class="card-header">
            {{ review.rate }} stars
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>{{ review.review }}</p>
              <footer class="blockquote-footer">{{ review.created|timesince }} ago by {{ review.user.username }}</footer>
            </blockquote>
          </div>
        </div>
    {% empty %}
        <h3>No reviews yet</h3>
    {% endfor %}

{#    create form #}
    <hr>
    <p>Write your review</p>
    <form method="post" action="/blogs/{{ blog.id }}/review/">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit Review">
    </form>

{% endblock %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
    <h2>Totle blogs : {{ blogs|length }}</h2>
<div class="row">
    {% for b in blogs %}
        <div class="card col-6">
          <img class="card-img-top" src="/media/{{ b.image }}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ b.title|title }}</h5>
            <p class="card-text">{{ b.description|truncatewords:5 }}</p>
            <p class="card-text">{{ b.created|timesince }}</p>
            <a href="/blogs/{{ b.id }}" class="btn btn-primary">View More</a>
          </div>
        </div>

    {% endfor %}
</div>
{% endblock %}

blogs/templates/blogs/login.html
{{ form.as_p }}

blogs/templates/blogs/signup.html
{{ form.as_p }}

polls/templates/polls/base.html
<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>Site administration | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css">

    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">

<meta name="robots" content="NONE,NOARCHIVE">
</head>

<body class=" dashboard"
  data-admin-utc-offset="20700">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a href="/admin/">Django administration</a></h1>

        </div>


        <div id="user-tools">

                Welcome,
                <strong>hereshem</strong>.



                    <a href="/">View site</a> /






                <a href="/admin/password_change/">Change password</a> /

                <a href="/admin/logout/">Log out</a>

        </div>



    </div>
    <!-- END Header -->


    {% block mycontent %}
        This is default content
    {% endblock %}

    <div>This is footer</div>

</div>
</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block mytitle %}{{ question.text }}{% endblock %}
{% block mycontent %}

<center>
<h1>{{ question.text }}</h1>
<form action="/polls/{{ question.id }}/vote/" method="post">
    {% csrf_token %}
    {% for ch in question.choice_set.all %}
        <p>
            {{ ch.text }} - {{ ch.vote }}
            <input type="radio" name="choice" value="{{ ch.id }}">
        </p>
    {% endfor %}
    <input type="submit" value="Submit Vote">
</form>
</center>

{%  endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{%  block mycontent %}

<h1>hello there from template</h1>

Jinga Templating Language

prints variable {{ hello }}

{% for q in questions %}

    <p> <a href="/polls/{{ q.id }}">{{ q.text }}</a> </p>

{% endfor %}


{% endblock %}

{% block mytitle %}Home Page{% endblock %}

{% block sdgsadkg %}jhbsdjhbajhbjbsadkbasd{% endblock %}
afjkb jkdshjhajhfadsjgh